### ISSUE TITLE
Bridge Discovery within apps

### ISSUE THREAD

**Issue by tube0013** [marcelveldt/hass_emulated_hue#2]
First up thanks for this addon - I have been chasing a method to use my HA lights in certain hue apps for ages in an attempt to move all my remaining hue lights to HA and drop the hue hub.

In particular I'm trying to get the Hue Disco (iOS) app working.  I've tried to add the emulated bridge but there is no manual entry and discovery fails, it only sees my existing hue bridge.  the only app I'm able to get working with the emulated hue bridge is the Hue Essentials App which supports manually entering a bridge ip.

For comparison, here is the discovery info picked up by ZeroConf Browser for the Hue bridge vs my the hass emulated bridge

Hue:
<img width="352" alt="Screen Shot 2020-02-13 at 10 23 11 AM" src="https://user-images.githubusercontent.com/11084412/74449688-e719de00-4e4a-11ea-80e1-24b89779ec20.png">

HASS:
<img width="501" alt="Screen Shot 2020-02-13 at 10 23 25 AM" src="https://user-images.githubusercontent.com/11084412/74449807-1cbec700-4e4b-11ea-802e-9bb47a6c752d.png">

**Comment by marcelveldt** [comment]
Make sure that nothing is blocking port 80 and 443 on your set-up. Check the logs of the addon if the HTTP and HTTPS server started succesfully...
![Schermafbeelding 2020-02-13 om 16 29 28](https://user-images.githubusercontent.com/6389780/74450203-041bd480-4e7e-11ea-9d3b-840b19cff77b.png)

**Comment by tube0013** [comment]
yup, I checked the 2 ports and disabled the built in hue emulation in HA (which was on 80) before initially deploying the addon.  just restarted and I get the same messages:

```
2020-02-13 15:40:48,121 INFO Set uid to user 0 succeeded
2020-02-13 15:40:48,123 INFO supervisord started with pid 6
2020-02-13 15:40:49,124 INFO spawned: 'hue' with pid 8
2020-02-13 15:40:49,711 INFO  emulated_hue.config.config -- Listen IP address not specified, auto-detected address is 192.168.1.221
2020-02-13 15:40:50,388 INFO  emulated_hue.hue_api.hue_api -- Started HTTP webserver on port 80
2020-02-13 15:40:50,389 INFO success: hue entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-13 15:40:50,393 INFO  emulated_hue.hue_api.hue_api -- Started HTTPS webserver on port 443
```

**Comment by marcelveldt** [comment]
Are you sure that the default emulated hue component is fully disabled as the broadcast message from zeroconf doesn't seem to match with the discovery info sent out by my code. ?

**Comment by marcelveldt** [comment]
Just came to my mind that I discovered that you might need to reinstall the Hue app.

**Comment by tube0013** [comment]
interesting, I have definitely removed the emulated hue config from my configuration.  yet the broadcast is definitely still coming from Home Assistant.  (can watch it pop up in avahi-browse as HA restarts with the addon shut down.

ill look into the ha debug logs to see if I can determine why this is happening....

**Comment by tube0013** [comment]
yea not seeing anything in logs.  so is  HA is blocking the port for the discovery message?  I even tried reconfigure the built in version to run or totally different ports.

**Comment by tube0013** [comment]
duh.. the "Home Assistant Bridge" is the HA HomeKit bridge not related to emulated hue.

So I am not seeing any discovery messages from the addon, with ports 80 and 443 open.

**Comment by marcelveldt** [comment]
Discovery is not zeroconf/bonjour. It's SSDP/upnp.
Did you try the official Hue app as a test |?

**Comment by tube0013** [comment]
yes I'm not able to connect the hue app, (ios)  I will need to try uninstalling and re-installing it still but it trigger the notification in HA I allow it and the app just times out.

In the disco hue app, the notification is triggered and then once I enable the app says something went wrong.

here's the log from the hue app time out.. nothing really there.

```
2020-02-14 13:03:32,582 INFO Set uid to user 0 succeeded
2020-02-14 13:03:32,583 INFO supervisord started with pid 6
2020-02-14 13:03:33,586 INFO spawned: 'hue' with pid 8
2020-02-14 13:03:34,076 INFO  emulated_hue.config -- Listen IP address not specified, auto-detected address is 192.168.1.221
2020-02-14 13:03:34,579 INFO  emulated_hue.hue_api -- Started HTTP webserver on port 80
2020-02-14 13:03:34,585 INFO  emulated_hue.hue_api -- Started HTTPS webserver on port 443
2020-02-14 13:03:34,585 INFO success: hue entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-02-14 13:03:41,380 INFO  emulated_hue.config -- Link request detected - Use the Homeassistant frontend to confirm this link request.
2020-02-14 13:03:58,882 INFO  emulated_hue.config -- Link mode is enabled for the next 60 seconds.

```

**Comment by tube0013** [comment]
I was able to connect to to the emulated hue bridge via the official Hue app, though it was a bit buggy and took a few attempts.  Still no dice with the disco hue app (or a few other hue apps I have from the same company that share the same connection code).

**Comment by marcelveldt** [comment]
Ok thanks for testing. Please define "it was a bit buggy" in more detail as it will help me to iron out the last flaws. In my own situation it works flawless but I have most certain forgotten about 1001 other scenarios ;-).

I will try myself with that Hue disco app to see if I can spot something.

**Comment by tube0013** [comment]
When the Hue app initialized the request I got the notification in HA and enabled linking. Hue app timed out, I tried it again and it seemed to time out again, but then when it exited out of linking, it was linked.  Basically it didn't link when linking was enabled, it timed out, then linked on 2nd try with no user notification in app. (This is from memory a few days ago now) - I will try again to see if it works.  If you want a donation to cover the app fee $3.99 I think, I'm happy to help out.

**Comment by tube0013** [comment]
so here's something interesting.. Have a test HA instance on a pi at work. it's on a subent just in my suite, and if I put my phone on that subnet and use the hue disco app, it scans and finds it and binds fine.  at home it no matter how many time I un-install it or try to clear out it's settings it aways tries my old hue ip whether it is online or not, and it never does a true scan.  I have a unifi secure gateway and access points at home.  guessing bad app discovery or my network to blame but not sure how to test it.  maybe a new ssid can get it to re-scan... hmmm

**Comment by tube0013** [comment]
On my home network with main HA install I eventually get this error:

```HueDiscoV3#SomeDevice registered
2020-02-20 23:57:11,341 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/app/emulated_hue/hue_api.py", line 71, in func_wrapper
    return await func(cls, request)
  File "/usr/local/app/emulated_hue/hue_api.py", line 389, in get_full_state
    "lights": await self.__get_all_lights(),
  File "/usr/local/app/emulated_hue/hue_api.py", line 689, in __get_all_lights
    entity_id = entity["entity_id"]
TypeError: 'NoneType' object is not subscriptable

**Comment by marcelveldt** [comment]
The latest version has a lot of fixes. Please test with that and report back (re-open this issue) if you still run into trouble. Thanks!
