### ISSUE TITLE
Can't add bridge in Android Hue App

### ISSUE THREAD

**Issue by Mr-Groch** [marcelveldt/hass_emulated_hue#39]
Fresh install, 0.0.6 version on RPI 3b 32 bit.
Emulated_Hue is detected in HUE app, link request notification appears, but after enabling link, error shows in log and pairing in hue app fails:

```
2020-12-30 22:54:25,867 DEBUG emulated_hue.api -- POST /api/
2020-12-30 22:54:25,868 DEBUG emulated_hue.api -- {'devicetype': 'Hue 3#Xiaomi MI 8 SE', 'generateclientkey': True}
2020-12-30 22:54:25,869 ERROR aiohttp.server -- Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/app/emulated_hue/api.py", line 79, in wrapped_func
    return await func(cls, request, request_data)
  File "/app/emulated_hue/api.py", line 183, in async_post_auth
    userdetails = await self.config.async_create_user(request_data["devicetype"])
  File "/app/emulated_hue/config.py", line 265, in async_create_user
    for item in all_users.values():
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by marcelveldt** [comment]
Oops, that's a sloppy error. I'll release a new version later today.

**Comment by marcelveldt** [comment]
New version is up (0.0.7) can you give that one a try ?

**Comment by Mr-Groch** [comment]
I'ts working now! Thanks!
